### ISSUE TITLE
Request contained an invalid body param

### ISSUE THREAD

**Issue by ilicmarko** [verbb/knock-knock#27]
### Description
When updated the Craft to the latest version `Craft CMS 3.4.20` Knock Knock stopped working. I open the page and I get the login screen when I enter the password it breaks.

```
yii\web\BadRequestHttpException: Request contained an invalid body param in /home/vagrant/code/vendor/craftcms/cms/src/web/Request.php:719
Stack trace:
#0 /home/vagrant/code/vendor/verbb/knock-knock/src/controllers/DefaultController.php(98): craft\web\Request->getValidatedBodyParam('redirect')
#1 [internal function]: verbb\knockknock\controllers\DefaultController->actionAnswer()
#2 /home/vagrant/code/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /home/vagrant/code/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /home/vagrant/code/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('answer', Array)
#5 /home/vagrant/code/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('answer', Array)
#6 /home/vagrant/code/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('knock-knock/def...', Array)
#7 /home/vagrant/code/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('knock-knock/def...', Array)
#8 /home/vagrant/code/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /home/vagrant/code/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /home/vagrant/code/web/index.php(21): yii\base\Application->run()
#11 {main}
```

![image](https://user-images.githubusercontent.com/2827249/83425057-9647e880-a42d-11ea-8e54-bb7706039d22.png)

I check the request everything is being sent as it should:

```
action: knock-knock/default/answer
redirect: http://site.test/our-work
CRAFT_CSRF_TOKEN: faIsXOcxbWSP_HjWExXUdZEWTMIzWTYp7qwNmiIp1CMmLRPv-y6DhFDGXgO3BhorzrA67mRcmj71TAeMXW1aZ7v2fNljfKZHYWVw15Vp29s=
password: test123
```

### Steps to reproduce

1. Open the page with Knock Knock
2. Enter any password

### Additional info

- Plugin version: `1.2.8`
- Craft version: `3.4.20`

**Comment by ilicmarko** [comment]
I traced the problem to `hash` filter not working inside the plugin. Basically this `{{ redirect | hash }}` doesn't output a hashed value.

I will investigate further when I get home.

**Comment by ilicmarko** [comment]
This was not a knock-knock issue, there was problem with the template and the `hash` filter. It resulted in not hashing the redirect and it wasn't validated.

Sorry for any problems.
